// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADuGukaoq50DLILGlINhLHULWCqasOuok',
    appId: '1:356781804304:web:2e8cb805753a245be0b395',
    messagingSenderId: '356781804304',
    projectId: 'talent-sphere-ai-bbeca',
    authDomain: 'talent-sphere-ai-bbeca.firebaseapp.com',
    storageBucket: 'talent-sphere-ai-bbeca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1wgjjFOBwIb5sHGla_cwW23wv_P5nLqI',
    appId: '1:356781804304:android:878bdc1db2b810a4e0b395',
    messagingSenderId: '356781804304',
    projectId: 'talent-sphere-ai-bbeca',
    storageBucket: 'talent-sphere-ai-bbeca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmdlHqGVcxPiDQ4FzrdqoRTTaPxca-xUE',
    appId: '1:356781804304:ios:0e4820fe8f1f8b59e0b395',
    messagingSenderId: '356781804304',
    projectId: 'talent-sphere-ai-bbeca',
    storageBucket: 'talent-sphere-ai-bbeca.firebasestorage.app',
    iosBundleId: 'com.example.talentPhereAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmdlHqGVcxPiDQ4FzrdqoRTTaPxca-xUE',
    appId: '1:356781804304:ios:0e4820fe8f1f8b59e0b395',
    messagingSenderId: '356781804304',
    projectId: 'talent-sphere-ai-bbeca',
    storageBucket: 'talent-sphere-ai-bbeca.firebasestorage.app',
    iosBundleId: 'com.example.talentPhereAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADuGukaoq50DLILGlINhLHULWCqasOuok',
    appId: '1:356781804304:web:65e62022758b48f0e0b395',
    messagingSenderId: '356781804304',
    projectId: 'talent-sphere-ai-bbeca',
    authDomain: 'talent-sphere-ai-bbeca.firebaseapp.com',
    storageBucket: 'talent-sphere-ai-bbeca.firebasestorage.app',
  );
}
